### ISSUE TITLE
ImportError import historical_data, 'Client' from 'binance'

### ISSUE THREAD

**Issue by mossene** [arabacibahadir/sup-res#5]
Hello, 
Trying to run python main.py, I got this errors, any solution ?

PS C:\Users\#####\Desktop\########\sup-res-master> python main.py
Traceback (most recent call last):
  File "sup-res-master\main.py", line 9, in <module>
    import historical_data
  File "sup-res-master\historical_data.py", line 4, in <module>
    from binance import Client
ImportError: cannot import name 'Client' from 'binance' (C:\Python39\lib\site-packages\binance\__init__.py)

![image](https://user-images.githubusercontent.com/40315904/147081907-01a981aa-aff4-4f35-8f47-ecbdd2ea61dc.png)

**Comment by arabacibahadir** [comment]
Hello,
Did you install all pip libraries and also did you change your binance api? 
https://github.com/arabacibahadir/sup-res#installation

**Comment by mossene** [comment]
Thanks for the fast reply.
Yes, I did.
Do API keys with read-Only work? or I need to enable Spot trading permission?

**Comment by arabacibahadir** [comment]
Yes, you can use read-only api. You don't need to give any other permissions.
If your problem persists, run a small ticker test and we can clarify the issue. Maybe you are having a problem with the api. 
https://python-binance.readthedocs.io/en/latest/overview.html

**Comment by mossene** [comment]
ticker test working good.

Uninstalled all the requirements and installed them again, but the same problem came up.

**Comment by arabacibahadir** [comment]
Can you try this for import?
`from binance.client import Client`

**Comment by mossene** [comment]
got this:
 
  from binance.client import Client
ModuleNotFoundError: No module named 'binance.client'

-- I tried to install binance.client, but the Requirement already satisfied.

**Comment by arabacibahadir** [comment]
Hey again, while pushing the code i forgot to update historical_data.py file with api_binance instead of binance_api, which is my local api file.
`client = Client(binance_api.api, binance_api.secret)   #this is old one`
`client = Client(api_binance.api, api_binance.secret)   #this is the new one`
 I changed this line should be working, i tried in my local. 
Updated code should fine right now. Please download again files and change your api. 
Do not hesitate to write if you have any problems. Thank you for your patience.
Note for myself: I should create a new branch for this, this was my fault.

**Comment by mossene** [comment]
The problem still here:

C:\Users\#####\Desktop\######\sup-res-master> python main.py
Traceback (most recent call last):
  File "C:\Users\#####\Desktop\####\sup-res-master\main.py", line 7, in <module>
    import historical_data
  File "C:\Users\mohce\Desktop\########\sup-res-master\historical_data.py", line 6, in <module>
    import frameselect
  File "C:\Users\#######\Desktop\########\sup-res-master\frameselect.py", line 1, in <module>
    from binance import Client
ImportError: cannot import name 'Client' from 'binance' (C:\Python39\lib\site-packages\binance\__init__.py)
PS C:\Users\#######\Desktop\########\sup-res-master>

**Comment by arabacibahadir** [comment]
https://github.com/sammchardy/python-binance/issues/316#issuecomment-766191768
Check this. You are probably getting a version error. Can you try a ide vscode, pycharm etc.?
People are complaining about python 3.9 site-package errors.

**Comment by mossene** [comment]
Well, nothing is working the same error everywhere, I will try to figure out to resolve this issue.

Thank you for your assistance and for your time. I will comeback to you if I have any updates.
